const express=require('express')
const { createBodycare, updateBodycare, deleteBodycare } = require('../controllers/bodycare.controller')
const { createHaircare, updateHaircare, deleteHaircare } = require('../controllers/haircare.controller')
const { createMakeup, updateMakeup, deleteMakeup } = require('../controllers/makeup.controller')
const { createSkincare, updateSkincare, deleteSkincare } = require('../controllers/skincare.controller')
const { createNail, updateNail, deleteNail } = require('../controllers/nail.controller')
const { createFragrance, updateFragrance, deleteFragrance } = require('../controllers/fragrance.controller')
const { protect, restrictTo } = require('../controllers/authControllers')
const router=express.Router()

router.route('/create/bodycare').post(protect,restrictTo("admin"),createBodycare)
router.route('/create/haircare').post(protect,restrictTo("admin"),createHaircare)
router.route('/create/makeup').post(protect,restrictTo("admin"),createMakeup)
router.route('/create/skincare').post(protect,restrictTo("admin"),createSkincare)
router.route('/create/nail').post(protect,restrictTo("admin"),createNail)
router.route('/create/fragrance').post(protect,restrictTo("admin"),createFragrance)

router.route('/update/bodycare/:id').put(protect,restrictTo("admin"),updateBodycare)
router.route('/update/haircare/:id').put(protect,restrictTo("admin"),updateHaircare)
router.route('/update/makeup/:id').put(protect,restrictTo("admin"),updateMakeup)
router.route('/update/skincare/:id').put(protect,restrictTo("admin"),updateSkincare)
router.route('/update/nail/:id').put(protect,restrictTo("admin"),updateNail)
router.route('/update/fragrance/:id').put(protect,restrictTo("admin"),updateFragrance)

router.route('/delete/bodycare/:id').delete(protect,restrictTo("admin"),deleteBodycare)
router.route('/delete/haircare/:id').delete(protect,restrictTo("admin"),deleteHaircare)
router.route('/delete/makeup/:id').delete(protect,restrictTo("admin"),deleteMakeup)
router.route('/delete/skincare/:id').delete(protect,restrictTo("admin"),deleteSkincare)
router.route('/delete/fragrance/:id').delete(protect,restrictTo("admin"),deleteFragrance)
router.route('/delete/nail/:id').delete(protect,restrictTo("admin"),deleteNail)
module.exports=router